Repository asterisk/asterisk, pull requests merged in 2023-05, with the labels that each got.

#57 core: Cleanup gerrit and JIRA references.
  .gitreview
  BUGS
  build_tools/make_version
  configs/samples/extensions.conf.sample
  configure
  configure.ac
  contrib/scripts/ast_grab_core
  contrib/scripts/sip_to_pjsip/sip_to_pjsip.py
  contrib/scripts/sip_to_pjsip/sip_to_pjsql.py
  doc/asterisk.8
  doc/asterisk.sgml
  include/asterisk/doxyref.h
  menuselect/README
Labels: test-checks-passed, test-gates-failed

#54 cel: add local optimization begin event
  include/asterisk/cel.h
  main/cel.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#59 chan_pjsip: also return all codecs on empty re-INVITE for late offers
  res/res_pjsip_session.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#61 core: Cleanup gerrit and JIRA references. (#40)
  .gitreview
  BUGS
  build_tools/make_version
  configs/samples/extensions.conf.sample
  configure
  configure.ac
  contrib/scripts/ast_grab_core
  contrib/scripts/sip_to_pjsip/sip_to_pjsip.py
  contrib/scripts/sip_to_pjsip/sip_to_pjsql.py
  doc/asterisk.8
  doc/asterisk.sgml
  include/asterisk/doxyref.h
  menuselect/README
Labels: test-checks-passed, test-gates-failed

#69 xml.c: Process XML Inclusions recursively.
  main/xml.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#79 utils.h: Deprecate `ast_gethostbyname()`.
  include/asterisk/utils.h
Labels: test-checks-passed, test-gates-failed

#56 res_sorcery_memory_cache.c: Fix memory leak.
  res/res_sorcery_memory_cache.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#76 res_pjsip_pubsub.c: Use pjsip version for pending NOTIFY check.
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  res/res_pjsip_pubsub.c
  third-party/pjproject/configure.m4
Labels: test-checks-passed, test-gates-failed

#77 res_pjsip_pubsub.c: Use pjsip version for pending NOTIFY check.
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  res/res_pjsip_pubsub.c
  third-party/pjproject/configure.m4
Labels: test-checks-passed, test-gates-failed

#82 res_pjsip_pubsub: Add new pubsub module capabilities.
  include/asterisk/res_pjsip_pubsub.h
  res/res_pjsip_pubsub.c
Labels: test-checks-passed, test-gates-passed

#103 asterisk.c: Fix option warning for remote console.
  doc/asterisk.8
  main/asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-passed

#101 chan_dahdi: Fix broken hidecallerid setting.
  channels/chan_dahdi.c
  channels/sig_analog.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed

#74 chan_pjsip: Allow topology/session refreshes in early media state
  channels/chan_pjsip.c
  include/asterisk/res_pjsip_session.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed

#97 logrotate: Fix duplicate log entries.
  contrib/scripts/asterisk.logrotate
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed

#99 callerid: Allow specifying timezone for date/time.
  include/asterisk/callerid.h
  main/callerid.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed
