Repository asterisk/asterisk, pull requests merged in 2023-09, with the labels that each got.

#290 variables: Add additional variable dialplan functions.
  funcs/func_global.c
  funcs/func_logic.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#300 chan_rtp: Implement RTP glue for UnicastRTP channels
  channels/chan_rtp.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#318 safe_asterisk: Change directory permissions to 755
  contrib/scripts/safe_asterisk
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#306 res_speech_aeap: check for null format on response
  res/res_speech_aeap.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#323 res_stasis_recording.c: Save recording state when unmuted.
  res/res_stasis_recording.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#326 func_periodic_hook: Add hangup step to avoid timeout
  funcs/func_periodic_hook.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#329 make_buildopts_h, et. al. Allow adding all cflags to buildopts.h
  Makefile
  build_tools/cflags.xml
  build_tools/make_buildopts_h
  build_tools/make_version_c
  include/asterisk/ast_version.h
  main/asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#302 res_rtp_asterisk: fix wrong counter management in ioqueue objects
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#287 chan_iax2: Improve authentication debugging.
  channels/chan_iax2.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#317 file.c: Add ability to search custom dir for sounds
  configs/samples/asterisk.conf.sample
  include/asterisk/options.h
  main/asterisk.c
  main/file.c
  main/manager.c
  main/options.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#309 chan_console: Fix deadlock caused by unclean thread exit.
  channels/chan_console.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#331 cel: add publish user event helper
  include/asterisk/cel.h
  main/cel.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#327 res_pjsip_transport_websocket: Prevent transport from being destroyed before message finishes.
  res/res_pjsip_transport_websocket.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#338 asterisk.c: Use the euid's home directory to read/write cli history
  main/asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#334 lock.c: Separate DETECT_DEADLOCKS from DEBUG_THREADS
  build_tools/cflags-devmode.xml
  include/asterisk/lock.h
  main/lock.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#219 maximum_ms changed to multiple of 20
  main/codec_builtin.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress
