Repository asterisk/asterisk, pull requests merged in 2023-06, with the labels that each got.

#67 apps/app_queue: Preserve reason for realtime queues
  apps/app_queue.c
  contrib/ast-db-manage/config/versions/4042a0ff4d9f_add_reason_paused_to_queue_members.py
Labels: cherry-pick-checks-failed, test-checks-passed, test-gates-failed

#92 res_stasis.c: Add new type 'sdp_label' for bridge creation.
  res/ari/resource_bridges.h
  res/res_stasis.c
  res/stasis/stasis_bridge.c
  res/stasis/stasis_bridge.h
  rest-api/api-docs/bridges.json
Labels: cherry-pick-checks-failed, test-checks-passed, test-gates-passed

#95 sig_analog: Add fuller Caller ID support.
  channels/chan_dahdi.c
  channels/sig_analog.c
  channels/sig_analog.h
  configs/samples/chan_dahdi.conf.sample
  funcs/func_callerid.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#105 AMI: Add CoreShowChannelMap action.
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#121 chan_dahdi: Fix Caller ID presentation for FXO ports.
  channels/chan_dahdi.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#137 configure: Makefile downloader enable follow redirects.
  configure
  configure.ac
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, test-gates-failed

#138 sounds: Update download URL to use HTTPS.
  sounds/Makefile
Labels: cherry-pick-checks-passed, cherry-pick-checks-failed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed

#148 ast-db-manage: Fix alembic branching error caused by #122.
  contrib/ast-db-manage/config/versions/f5b0e7427449_add_loop_last_to_res_musiconhold.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed

#157 build: Fix a few gcc 13 issues
  include/asterisk/app.h
  main/loader.c
  main/stasis_message.c
  tests/test_utils.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#160 build: Fix a few gcc 13 issues
  include/asterisk/app.h
  main/loader.c
  main/stasis_message.c
  tests/test_utils.c
Labels: test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#159 test_stasis_endpoints.c: Make channel_messages more stable
  tests/test_stasis_endpoints.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#106 AMI: Add parking position parameter to Park action
  res/parking/parking_manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#141 tcptls: when disabling a server port, we should set the accept_fd to -1.
  main/tcptls.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#124 res_fax_spandsp.c: Clean up a spaces/tabs issue
  res/res_fax_spandsp.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#140 configure: Remove obsolete and deprecated constructs.
  autoconf/ax_pthread.m4
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  menuselect/configure.ac
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#109 app_queue: Add force_longest_waiting_caller option.
  apps/app_queue.c
  configs/samples/queues.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#154 res_pjsip_session: Added new function calls to avoid ABI issues.
  include/asterisk/res_pjsip_session.h
  res/res_pjsip_session.c
Labels: test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#153 res_pjsip_session: Added new function calls to avoid ABI issues.
  include/asterisk/res_pjsip_session.h
  res/res_pjsip_session.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#177 rest-api: Updates for new documentation site
  Makefile
  rest-api-templates/api.wiki.mustache
  rest-api-templates/make_ari_stubs.py
  rest-api-templates/models.wiki.mustache
  rest-api-templates/swagger_model.py
Labels: test-checks-passed, pre-merge-checks-passed, merge-in-progress

#111 utils: add lock timestamps for DEBUG_THREADS
  main/utils.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#134 res_musiconhold: avoid moh state access on unlocked chan
  res/res_musiconhold.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#175 app_voicemail: fix imap compilation errors
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, testing-in-progress, test-checks-passed, pre-merge-checks-passed, merge-in-progress
