Repository asterisk/asterisk, pull requests merged in 2023-12, with the labels that each got.

#456 config.c: Log #exec include failures.
  main/config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#478 res_pjsip_header_funcs.c: Check URI parameter length before copying.
  res/res_pjsip_header_funcs.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#466 res_odbc.c: Allow concurrent access to request odbc connections
  res/res_odbc.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#468 logger.c: Move LOG_GROUP documentation to dedicated XML file.
  main/logger.c
  main/logger.xml
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#446 ast_coredumper: Increase reliability
  contrib/scripts/ast_coredumper
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#471 pbx_config.c: Don't crash when unloading module.
  pbx/pbx_config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#464 app_dial: Add option "j" to preserve initial stream topology of caller
  apps/app_dial.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#431 general: Fix broken links.
  BUGS
  README-SERIOUSLY.bestpractices.md
  README.md
  apps/app_audiosocket.c
  apps/app_skel.c
  apps/app_voicemail.c
  apps/confbridge/include/conf_state.h
  configs/basic-pbx/README
  configs/samples/ccss.conf.sample
  configs/samples/chan_dahdi.conf.sample
  configs/samples/extconfig.conf.sample
  configs/samples/geolocation.conf.sample
  configs/samples/pjsip.conf.sample
  configs/samples/pjsip_wizard.conf.sample
  configs/samples/sla.conf.sample
  configs/samples/stir_shaken.conf.sample
  doc/CODING-GUIDELINES
  doc/README.txt
  doc/asterisk.8
  doc/asterisk.sgml
  doc/lang/language-criteria.txt
  main/ast_expr2.fl
  main/ast_expr2f.c
  main/asterisk.c
  main/config.c
  main/pbx_functions.c
  main/stasis.c
  res/ari/resource_channels.h
  res/res_ari.c
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip_config_wizard.c
  res/res_srtp.c
  res/res_timing_dahdi.c
  rest-api/api-docs/channels.json
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#469 make_xml_documentation: Really collect LOCAL_MOD_SUBDIRS documentation.
  build_tools/make_xml_documentation
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#483 manager.c: Improve clarity of "manager show connected".
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#498 res_pjsip: disable raw bad packet logging
  configs/samples/pjproject.conf.sample
  res/res_pjproject.c
  third-party/pjproject/patches/0220-log-dropped-packet-in-debug.patch
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#494 manager.c: Prevent path traversal with GetConfig.
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#495 res_rtp_asterisk.c: Check DTLS packets against ICE candidate list
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#496 res_pjsip: disable raw bad packet logging
  configs/samples/pjproject.conf.sample
  res/res_pjproject.c
  third-party/pjproject/patches/0020-log-dropped-packet-in-debug.patch
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#497 res_pjsip_header_funcs: Duplicate new header value, don't copy.
  res/res_pjsip_header_funcs.c
Labels: cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#501 doc: Remove obsolete CHANGES-staging and UPGRADE-staging directories
  doc/CHANGES-staging/README.md
  doc/CHANGES-staging/http_bindaddr.txt
  doc/UPGRADE-staging/README.md
  doc/UPGRADE-staging/app_cdr.txt
  doc/UPGRADE-staging/app_macro_removal.txt
  doc/UPGRADE-staging/app_osplookup_removal.txt
  doc/UPGRADE-staging/chan_alsa_removal.txt
  doc/UPGRADE-staging/chan_mgcp_removal.txt
  doc/UPGRADE-staging/chan_sip_removal.txt
  doc/UPGRADE-staging/chan_skinny_removal.txt
  doc/UPGRADE-staging/pbx_builtins.txt
  doc/UPGRADE-staging/res_monitor_removal.txt
  doc/UPGRADE-staging/translate.txt
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#502 doc: Remove obsolete CHANGES-staging directrory
  doc/CHANGES-staging/app_directory_skip_call.txt
  doc/CHANGES-staging/app_read_return_terminator.txt
  doc/CHANGES-staging/app_senddtmf_answer.txt
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#506 res_rtp_asterisk: Fix regression issues with DTLS client check
  include/asterisk/res_pjproject.h
  res/res_pjproject.c
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
