Repository asterisk/asterisk, pull requests merged in 2023-07, with the labels that each got.

#187 pjsip: Upgrade bundled version to pjproject 2.13.1
  third-party/pjproject/pjproject-2.13.1.tar.bz2.md5
  third-party/pjproject/pjproject-2.13.tar.bz2.md5
  third-party/versions.mak
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#191 bundled_pjproject: Backport security fixes from pjproject 2.13.1
  third-party/pjproject/patches/0300-Merge-pull-request-from-GHSA-9pfh-r8x4-w26w.patch
  third-party/pjproject/patches/0301-Merge-pull-request-from-GHSA-cxwq-5g9x-x7fr.patch
  third-party/pjproject/patches/0302-Locking-fix-so-that-SSL_shutdown-and-SSL_write-are-n.patch
  third-party/pjproject/patches/0303-Don-t-call-SSL_shutdown-when-receiving-SSL_ERROR_SYS.patch
Labels: test-checks-passed, test-gates-failed

#190 bundled_pjproject: Backport security fixes from pjproject 2.13.1
  third-party/pjproject/patches/0300-Merge-pull-request-from-GHSA-9pfh-r8x4-w26w.patch
  third-party/pjproject/patches/0301-Merge-pull-request-from-GHSA-cxwq-5g9x-x7fr.patch
  third-party/pjproject/patches/0302-Locking-fix-so-that-SSL_shutdown-and-SSL_write-are-n.patch
  third-party/pjproject/patches/0303-Don-t-call-SSL_shutdown-when-receiving-SSL_ERROR_SYS.patch
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#195 bundled_pjproject: Backport 2 SSL patches from upstream
  third-party/pjproject/patches/0250-Fix-double-free-of-ossock-ossl_ctx-in-case-of-errors.patch
  third-party/pjproject/patches/0251-free-SSL-context-and-reset-context-pointer-when-sett.patch
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#196 apply_patches: Use globbing instead of file/sort.
  configure
  configure.ac
  makeopts.in
  third-party/apply_patches
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#119 sig_analog: Allow immediate fake ring to be suppressed.
  channels/chan_dahdi.c
  channels/chan_dahdi.h
  channels/sig_analog.c
  channels/sig_analog.h
  configs/samples/chan_dahdi.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#184 users.conf: Deprecate users.conf configuration.
  configs/samples/users.conf.sample
  pbx/pbx_config.c
Labels: test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#185 res_rtp_asterisk: Move ast_rtp_rtcp_report_alloc using `rtp->themssrc_valid` into the scope of the rtp_instance lock.
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#171 app_voicemail: add CLI commands for message manipulation
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#182 app_voicemail - add manager actions to display and manipulate messages
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#197 res_geolocation: Ensure required 'location_info' is present.
  res/res_geolocation/geoloc_config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#198 chan_iax2.c: Avoid crash with IAX2 switch support.
  channels/chan_iax2.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#199 doc: Remove obsolete CHANGES-staging and UPGRADE-staging
  doc/CHANGES-staging/README.md
  doc/CHANGES-staging/ami_hook_flash.txt
  doc/CHANGES-staging/app_mixmonitor_mute_by_id.txt
  doc/CHANGES-staging/bridge_builtin_features_beep_on_monitor.txt
  doc/CHANGES-staging/cli_channel_display_length_increase.txt
  doc/CHANGES-staging/dundi.txt
  doc/CHANGES-staging/format_sln_support_for_slin.txt
  doc/CHANGES-staging/res_http_media_cache.txt
  doc/CHANGES-staging/test.txt
  doc/UPGRADE-staging/README.md
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#201 app.h: Move declaration of ast_getdata_result before its first use
  include/asterisk/app.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#203 app_queue: Add support for applying caller priority change immediately.
  apps/app_queue.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#209 func_export: Use correct function argument as variable name.
  funcs/func_export.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#214 extensions.conf.sample: Remove reference to missing context.
  configs/samples/extensions.ael.sample
  configs/samples/extensions.conf.sample
  configs/samples/extensions.lua.sample
  configs/samples/iax.conf.sample
Labels: cherry-pick-checks-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#217 extensions.conf.sample: Remove reference to missing context.
  configs/samples/extensions.ael.sample
  configs/samples/extensions.conf.sample
  configs/samples/extensions.lua.sample
  configs/samples/iax.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress
