Repository asterisk/asterisk, pull requests merged in 2023-10, with the labels that each got.

#355 app_voicemail: Disable ADSI if unavailable.
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#342 func_json: Fix crashes for some types
  funcs/func_json.c
  include/asterisk/json.h
  main/json.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#295 chan_dahdi: Clarify scope of callgroup/pickupgroup.
  channels/chan_dahdi.c
  configs/samples/chan_dahdi.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#353 res_pjsip: update qualify_timeout documentation with DNS note
  res/res_pjsip/pjsip_config.xml
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-checks-failed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#366 logger.h: Add ability to change the prefix on SCOPE_TRACE output
  include/asterisk/logger.h
Labels: cherry-pick-checks-failed, test-checks-passed, test-checks-failed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#372 logger.h: Add ability to change the prefix on SCOPE_TRACE output
  include/asterisk/logger.h
Labels: test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#370 func_curl.c: Ensure channel is locked when manipulating datastores.
  funcs/func_curl.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#369 ari/stasis: Indicate progress before playback on a bridge
  res/ari/resource_bridges.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#363 res_stasis: signal when new command is queued
  res/res_stasis.c
  res/stasis/control.c
  res/stasis/control.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-checks-failed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#364 res_pjsip: Expanding PJSIP endpoint ID and relevant resource length to 255 characters
  contrib/ast-db-manage/config/versions/dac2b4c328b8_incease_pjsip_id_length.py
  include/asterisk/res_pjsip.h
  res/ari/internal.h
  res/res_pjsip/pjsip_distributor.c
  res/res_pjsip_authenticator_digest.c
  res/res_pjsip_endpoint_identifier_user.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#380 res_pjsip_exten_state,res_pjsip_mwi: Allow unload on shutdown
  res/res_pjsip_exten_state.c
  res/res_pjsip_mwi.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#375 configs: Fix typo in pjsip.conf.sample.
  configs/samples/pjsip.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#383 pjsip_configuration.c: Disable DTLS renegotiation if WebRTC is enabled.
  res/res_pjsip/pjsip_configuration.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#385 api.wiki.mustache: Fix indentation in generated markdown
  rest-api-templates/api.wiki.mustache
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#392 res_pjsip_dtmf_info.c: Add 'INFO' to Allow header.
  res/res_pjsip_dtmf_info.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#387 res_rtp_asterisk.c: Fix memory leak in ephemeral certificate creation.
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#305 res_speech: allow speech to translate input channel
  res/res_speech.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#403 bridge_simple: Suppress unchanged topology change requests
  bridges/bridge_simple.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
