Repository asterisk/asterisk, pull requests merged in 2023-11, with the labels that each got.

#400 app_queue.c: Emit unpause reason with PauseQueueMember event.
  apps/app_queue.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#399 app_voicemail: Add AMI event for mailbox PIN changes.
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#361 Remove UPGRADE.txt and CHANGES
  CHANGES
  UPGRADE.txt
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#249 core_local: Fix local channel parsing with slashes.
  main/core_local.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#357 app_directory: Add ADSI support to Directory.
  apps/app_directory.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#408 res_rtp_asterisk.c: Fix runtime issue with LibreSSL
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#407 main/utils: Implement ast_get_tid() for OpenBSD
  main/utils.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#410 chan_dahdi: Warn if nonexistent cadence is requested.
  channels/chan_dahdi.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#415 chan_iax2.c: Ensure all IEs are displayed when dumping frame contents.
  channels/iax2/parser.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#405 chan_pjsip: Add PJSIPHangup dialplan app and manager action
  channels/chan_pjsip.c
  channels/pjsip/dialplan_functions.c
  channels/pjsip/dialplan_functions.xml
  channels/pjsip/include/dialplan_functions.h
  include/asterisk/manager.h
  include/asterisk/res_pjsip.h
  main/manager.c
  res/res_pjsip.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#416 resource_channels.c: Explicit codec request when creating UnicastRTP.
  res/ari/resource_channels.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#419 codec_ilbc: Disable system ilbc if version >= 3.0.0
  configure
  configure.ac
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#420 chan_iax2.c: Don't send unsanitized data to the logger.
  channels/iax2/parser.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#243 logger: Add channel-based filtering.
  main/logger.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#426 configs: Improve documentation for bandwidth in iax.conf.
  configs/samples/iax.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#389 app_followme.c: Grab reference on nativeformats before using it
  apps/app_chanisavail.c
  apps/app_followme.c
  main/bridge.c
  main/bridge_basic.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#424 func_lock: Add missing see-also refs to documentation.
  funcs/func_lock.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#422 live_ast: Add astcachedir to generated asterisk.conf.
  contrib/scripts/live_ast
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#434 res_http_websocket.c: Set hostname on client for certificate validation.
  main/tcptls.c
  res/res_http_websocket.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#448 func_curl.c: Remove CURLOPT() plaintext documentation.
  funcs/func_curl.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#435 uri.c: Simplify ast_uri_make_host_with_port()
  main/uri.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#418 app.c: Allow ampersands in playback lists to be escaped.
  apps/app_authenticate.c
  apps/app_confbridge.c
  apps/app_playback.c
  apps/app_queue.c
  apps/app_read.c
  apps/app_skel.c
  apps/app_speech_utils.c
  main/app.c
  main/pbx_builtins.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#443 func_channel: Expose previously unsettable options.
  channels/chan_dahdi.c
  funcs/func_channel.c
  include/asterisk/frame.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#451 alembic: Update list of TLS methods available on ps_transports.
  contrib/ast-db-manage/.gitignore
  contrib/ast-db-manage/config/versions/37a5332640e2_update_pjsip_tls_method_list.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#453 res_rtp_asterisk.c: Update for OpenSSL 3+.
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#459 sig_analog: Fix channel leak when mwimonitor is enabled.
  channels/sig_analog.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#461 make_xml_documentation: Properly handle absolute LOCAL_MOD_SUBDIRS.
  build_tools/make_xml_documentation
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
