Repository asterisk/asterisk, pull requests merged in 2023-08, with the labels that each got.

#216 func_cut: Add example to documentation.
  funcs/func_cut.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#222 res_pjsip: Enable TLS v1.3 if present.
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  res/res_pjsip/config_transport.c
  res/res_pjsip/pjsip_config.xml
  third-party/pjproject/configure.m4
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#85 res_prometheus: Do not generate broken metrics
  res/prometheus/bridges.c
  tests/test_res_prometheus.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#206 sig_analog: Allow three-way flash to time out to silence.
  channels/chan_dahdi.c
  channels/chan_dahdi.h
  channels/sig_analog.c
  channels/sig_analog.h
  configs/samples/chan_dahdi.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#225 chan_dahdi: Allow autoreoriginating after hangup.
  channels/chan_dahdi.c
  channels/chan_dahdi.h
  configs/samples/chan_dahdi.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#72 core/ari/pjsip: Add refer mechanism
  include/asterisk/_private.h
  include/asterisk/refer.h
  include/asterisk/res_pjsip.h
  main/asterisk.c
  main/refer.c
  res/ari/resource_endpoints.c
  res/ari/resource_endpoints.h
  res/res_ari_endpoints.c
  res/res_pjsip.c
  res/res_pjsip_messaging.c
  res/res_pjsip_nat.c
  res/res_pjsip_refer.c
  rest-api/api-docs/endpoints.json
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#236 manager: Tolerate stasis messages with no channel snapshot.
  main/manager_channels.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#256 pjproject_bundled: Increase PJSIP_MAX_MODULE to 38
  third-party/pjproject/patches/config_site.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#250 res_pjsip_header_funcs: Make prefix argument optional.
  res/res_pjsip_header_funcs.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#239 rest-api: Run make ari-stubs
  res/ari/resource_endpoints.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#252 extconfig: Allow explicit DB result set ordering to be disabled.
  configs/samples/res_config_odbc.conf.sample
  configs/samples/res_pgsql.conf.sample
  res/res_config_odbc.c
  res/res_config_pgsql.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#232 res_pjsip.c: Add the contact_user to the Contact header
  res/res_pjsip.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#38 install_prereq: Fix dependency install on aarch64.
  contrib/scripts/install_prereq
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#254 Revert "app_stack: Print proper exit location for PBXless channels."
  apps/app_stack.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#262 Remove .lastclean and .version from source control
  .lastclean
  .version
Labels: test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#266 app_macro: Fix locking around datastore access
  apps/app_macro.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#264 download_externals: Fix a few version related issues
  build_tools/download_externals
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#270 app_audiosocket: Fixed timeout with -1 to avoid busy loop.
  apps/app_audiosocket.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress

#283 app_voicemail: Fix for loop declarations
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#282 app_dial: Fix infinite loop when sending digits.
  apps/app_dial.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-failed, pre-merge-checks-passed, merge-in-progress

#279 res_pjsip_session: Send Session Interval too small response
  res/res_pjsip_session.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, test-checks-passed, test-gates-passed, pre-merge-checks-passed, merge-in-progress
