Repository asterisk/asterisk, pull requests merged in 2024-09, with the labels that each got.

#857 res_pjsip_sdp_rtp fix leaking astobj2 ast_format
  main/rtp_engine.c
  res/res_pjsip_sdp_rtp.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#846 security_agreements.c: Refactor the to_str functions and fix a few other bugs
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip/security_agreements.c
  res/res_pjsip_outbound_registration.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, pr-submit-tests-passed

#848 res_pjsip_sdp_rtp: Use negotiated DTMF Payload types on bitrate mismatch
  include/asterisk/rtp_engine.h
  main/rtp_engine.c
  res/res_pjsip_sdp_rtp.c
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#866 app_voicemail: Use ast_asprintf to create mailbox SQL query
  apps/app_voicemail.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#865 app_voicemail: Fix sql insert mismatch caused by cherry-pick
  apps/app_voicemail.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#869 res_resolver_unbound: Test for NULL ub_result in unbound_resolver_callback
  main/dns_core.c
  res/res_resolver_unbound.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#868 autoservice: Do not sleep if autoservice_stop is called within autoservice thread
  main/autoservice.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#877 app_chanspy.c: resolving the issue writing frame to whisper audiohook.
  apps/app_broadcast.c
  apps/app_chanspy.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#885 res_stir_shaken.c: Fix crash when stir_shaken.conf is invalid
  res/res_stir_shaken.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#890 res_stir_shaken: Remove stale include for jansson.h in verification.c
  res/res_stir_shaken/verification.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#883 db.c: Remove limit on family/key length
  main/db.c
  tests/test_db.c
  tests/test_media_cache.c
Labels: cherry-pick-checks-failed, pre-merge-checks-failed, merge-in-progress, pr-submit-tests-passed

#874 manager: Enhance event filtering for performance
  configs/samples/manager.conf.sample
  main/manager.c
  main/manager_doc.xml
Labels: cherry-pick-checks-failed, pre-merge-checks-failed, merge-in-progress, pr-submit-tests-passed

#906 manager.conf.sample: Fix mathcing typo
  configs/samples/manager.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-failed, merge-in-progress, pr-submit-tests-failed

#892 Fix application references to Background
  apps/app_playback.c
  main/pbx_builtins.c
Labels: cherry-pick-checks-failed, pre-merge-checks-failed, merge-failed, merge-in-progress, pr-submit-tests-failed

#905 stir_shaken: Fix propagation of attest_level and a few other values
  res/res_stir_shaken/common_config.c
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/tn_config.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-failed, merge-in-progress, pr-submit-tests-failed

#898 res_pjsip_pubsub: Persist subscription 'generator_data' in sorcery
  contrib/ast-db-manage/config/versions/801b9fced8b7_add_generator_data_to_ps_subscription_.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#893 cel_custom: Allow absolute filenames.
  cel/cel_custom.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#894 channel: Value CHANNEL(userfield) is lost by BRIDGE_ENTER/BRIDGE_LEAVE.
  main/channel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#901 astfd.c: Avoid calling fclose with NULL argument.
  main/astfd.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#808 res_agi.c: In the speech recognition module, set fr to NULL after ast_frfree(fr).
  res/res_agi.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress

#909 manager.c: Restrict ModuleLoad to the configured modules directory.
  main/manager.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
