Repository asterisk/asterisk, pull requests merged in 2024-10, with the labels that each got.

#888 res_rtp_asterisk: Fix dtls timer issues causing FRACKs and SEGVs
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#917 main, res, tests: Fix compilation errors on FreeBSD.
  main/asterisk.c
  main/config.c
  main/manager.c
  res/res_timing_kqueue.c
  tests/test_crypto.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#926 res_agi.c: Ensure SIGCHLD handler functions are properly balanced.
  apps/app_voicemail.c
  include/asterisk/app.h
  main/asterisk.c
  res/res_agi.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#915 alembic: Drop redundant voicemail_messages index.
  contrib/ast-db-manage/voicemail/versions/64fae6bbe7fb_drop_redundant_index.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#933 manager.c: Add unit test for Originate app and appdata permissions (cert-18.9 & cert-20.7 only)
  main/manager.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#929 chan_dahdi: Never send MWI while off-hook.
  channels/chan_dahdi.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#939 geolocation.sample.conf: Fix comment marker at end of file
  configs/samples/geolocation.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#925 dnsmgr.c: dnsmgr_refresh() incorrectly flags change with DNS round-robin
  include/asterisk/acl.h
  main/acl.c
  main/dnsmgr.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#947 core_unreal.c: Fix memory leak in ast_unreal_new_channels() (cert-18.9 only)
  main/core_unreal.c
  main/stream.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#946 core_unreal.c: Fix memory leak in ast_unreal_new_channels()
  main/core_unreal.c
  main/stream.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#955 chan_sip.c: Fix `__sip_reliable_xmit` build error
  channels/chan_sip.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#953 pjproject_bundled: Tweaks to support out-of-tree development
  third-party/pjproject/Makefile
  third-party/pjproject/Makefile.rules
  third-party/pjproject/README-hacking.md
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#949 app_dial: Fix progress timeout calculation with no answer timeout.
  apps/app_dial.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
