Repository asterisk/asterisk, pull requests merged in 2024-04, with the labels that each got.

#678 cli.c: `core show channels concise` is not really deprecated.
  main/cli.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#677 Fix incorrect application and function documentation references - 21 and master
  apps/app_mixmonitor.c
  apps/app_stack.c
  channels/chan_iax2.c
  main/pbx_builtins.c
  res/res_fax.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, pr-submit-tests-passed

#680 res_stir_shaken: Fix compilation for CentOS7 (openssl 1.0.2)
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/crypto_utils.c
  res/res_stir_shaken/crypto_utils.h
  res/res_stir_shaken/verification_config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#602 res_pjsip_endpoint_identifier_ip: Add endpoint identifier transport address
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/d5122576cca8_add_transport_attribute_to_identify.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_endpoint_identifier_ip.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#674 chan_dahdi: Add DAHDIShowStatus AMI action.
  channels/chan_dahdi.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#684 func_callerid: Emit warning if invalid redirecting reason set.
  funcs/func_callerid.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#690 manager.c: Add missing parameters to Login documentation
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#687 rtp_engine and stun: call ast_register_atexit instead of ast_register_cleanup
  main/rtp_engine.c
  main/stun.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#697 alembic: Correct NULLability of PJSIP id columns.
  contrib/ast-db-manage/config/versions/6c475a93f48a_correct_nullability_of_pjsip_id_columns.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#701 alembic: Correct NULLability of PJSIP id columns. (certified/20.7)
  contrib/ast-db-manage/config/versions/6c475a93f48a_correct_nullability_of_pjsip_id_columns.py
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#703 file.c, channel.c: Don't emit warnings if progress received.
  main/channel.c
  main/file.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#708 app_queue.c: Properly handle invalid strategies from realtime.
  apps/app_queue.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#711 logger.h: Add SCOPE_CALL and SCOPE_CALL_WITH_RESULT
  include/asterisk/logger.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#682 callerid.c: Parse previously ignored Caller ID parameters.
  channels/chan_dahdi.c
  funcs/func_callerid.c
  include/asterisk/callerid.h
  main/callerid.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#709 sorcery.c: Fixed crash error when executing "module reload" with sorcery cache registration and res_prometeus
  main/sorcery.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#717 stir_shaken: Fix memory leak, typo in config, tn canonicalization
  configs/samples/stir_shaken.conf.sample
  res/res_pjsip_stir_shaken.c
  res/res_stir_shaken/attestation.c
  res/res_stir_shaken/common_config.c
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/tn_config.c
  res/res_stir_shaken/verification.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#715 tcptls/iostream: Add support for setting SNI on client TLS connections - cert/18.9 only
  include/asterisk/iostream.h
  main/iostream.c
  main/tcptls.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#714 tcptls/iostream: Add support for setting SNI on client TLS connections
  include/asterisk/iostream.h
  main/iostream.c
  main/tcptls.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#706 Initial RTP inactivity check must consider the rtp_timeout setting.
  res/res_pjsip_sdp_rtp.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#526 say.c: Fix cents off-by-one due to floating point rounding.
  funcs/func_sayfiles.c
  main/say.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#549 app_record: Add RECORD_TIME output variable.
  apps/app_record.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#726 Revert "app_record: Add RECORD_TIME output variable."
  apps/app_record.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#722 logger: Add unique verbose prefixes for levels 5-10.
  include/asterisk/logger.h
  main/asterisk.c
  main/logger.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
