Repository asterisk/asterisk, pull requests merged in 2024-07, with the labels that each got.

#787 logger.h: Include SCOPE_CALL_WITH_INT_RESULT() in non-dev-mode builds.
  include/asterisk/logger.h
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#791 security_agreement.c: Always add the Require and Proxy-Require headers
  res/res_pjsip/security_agreements.c
  res/res_pjsip_outbound_registration.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#798 ast-db-manage: Remove duplicate enum creation
  contrib/ast-db-manage/config/versions/2b7c507d7d12_add_queue_log_option_log_restricted_.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#779 res_pjsip_sdp_rtp: Add support for default/mismatched 8K RFC 4733/2833 digits
  include/asterisk/rtp_engine.h
  res/res_pjsip_sdp_rtp.c
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#732 res_pjsip_path.c: Fix path when dialing using PJSIP_DIAL_CONTACTS()
  res/res_pjsip_path.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#820 voicemail.conf.sample: Fix ':' comment typo
  configs/samples/voicemail.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#817 res_pjsip_config_wizard.c: Refactor load process
  res/res_pjsip_config_wizard.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#815 stir_shaken: CRL fixes and a new CLI command
  configs/samples/stir_shaken.conf.sample
  res/res_stir_shaken/attestation_config.c
  res/res_stir_shaken/common_config.c
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/crypto_utils.c
  res/res_stir_shaken/crypto_utils.h
  res/res_stir_shaken/profile_config.c
  res/res_stir_shaken/stir_shaken_doc.xml
  res/res_stir_shaken/verification_config.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#823 rtp_engine.c: Prevent segfault in ast_rtp_codecs_payloads_unset()
  main/rtp_engine.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
