Repository asterisk/asterisk, pull requests merged in 2024-03, with the labels that each got.

#635 Makefile: Add stir_shaken/cache to directories created on install
  Makefile
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#637 attestation_config.c: Use ast_free instead of ast_std_free
  res/res_stir_shaken/attestation_config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#625 res_pjsip: Use consistent type for boolean columns.
  contrib/ast-db-manage/config/versions/74dc751dfe8e_more_permission_boolean_columns.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#620 app_voicemail: Allow preventing mark messages as urgent.
  apps/app_voicemail.c
  configs/samples/voicemail.conf.sample
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#550 app_queue.c : fix "queue add member" usage string
  apps/app_queue.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#630 app_voicemail: Properly reinitialize config after unit tests.
  apps/app_voicemail.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-testing-in-progress

#589 app_dial: Add dial time for progress/ringing.
  apps/app_dial.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#640 res_monitor.c: Don't emit a warning about 'X' being unrecognized.
  res/res_monitor.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#612 res_pjsip_session: Reset pending_media_state->read_callbacks
  res/res_pjsip_session.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#652 alembic: Quote new MySQL keyword 'qualify.'
  contrib/ast-db-manage/config/versions/4da0c5f79a9c_create_tables.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#649 Upgrade bundled pjproject to 2.14.1
  third-party/pjproject/pjproject-2.14.1.tar.bz2.md5
  third-party/pjproject/pjproject-2.14.tar.bz2.md5
  third-party/versions.mak
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#658 res_pjsip: Fix alembic downgrade for boolean columns.
  contrib/ast-db-manage/config/versions/74dc751dfe8e_more_permission_boolean_columns.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#486 manager.c: Add CLI command to kick AMI sessions.
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#631 res_prometheus: Fix duplicate output of metric and help text
  res/prometheus/bridges.c
  tests/test_res_prometheus.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#663 pbx_variables.c: Prevent SEGV due to stack overflow.
  main/pbx_variables.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#481 pbx_variables.c: Prevent SEGV due to stack overflow.
  main/pbx_variables.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#662 menuselect: Minor cosmetic fixes.
  menuselect/menuselect.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#650 manager.c: Add new parameter 'PreDialGoSub' to Originate AMI action.
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#659 alembic: Fix compatibility with SQLAlchemy 2.0+.
  contrib/ast-db-manage/env.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#667 res_ari.c: Add additional output to ARI requests when debug is enabled
  res/res_ari.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#580 res_pjsip_refer.c: Allow GET_TRANSFERRER_DATA
  res/res_pjsip_refer.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#670 chan_dahdi: Don't retry opening nonexistent channels on restart.
  channels/chan_dahdi.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#600 res_pjsip_endpoint_identifier_ip: Endpoint identifier request URI
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/cf150a175fd3_add_match_request_uri_attribute_to_.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_endpoint_identifier_ip.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
