Repository asterisk/asterisk, pull requests merged in 2024-08, with the labels that each got.

#828 res_pjsip_sdp_rtp.c: Fix DTMF Handling in Re-INVITE with dtmf_mode set to auto
  res/res_pjsip_sdp_rtp.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#802 res_stasis: fix intermittent delays on adding channel to bridge
  res/res_stasis.c
  res/stasis/control.c
  res/stasis/control.h
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#834 manager.c: Add entries to Originate blacklist
  main/manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#814 feat: ARI "ChannelToneDetected" event
  configs/samples/stasis.conf.sample
  include/asterisk/stasis_channels.h
  main/stasis.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/res_tonedetect.c
  rest-api/api-docs/events.json
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#830 configure: Use . file rather than source file.
  configure
  configure.ac
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#743 channel: Add multi-tenant identifier. cert-18.9
  cel/cel_manager.c
  channels/chan_pjsip.c
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
  funcs/func_channel.c
  include/asterisk/cdr.h
  include/asterisk/cel.h
  include/asterisk/channel.h
  include/asterisk/channel_internal.h
  include/asterisk/event_defs.h
  include/asterisk/res_pjsip.h
  include/asterisk/stasis_channels.h
  main/cdr.c
  main/cel.c
  main/channel.c
  main/channel_internal_api.c
  main/cli.c
  main/event.c
  main/manager_channels.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  rest-api/api-docs/channels.json
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#742 channel: Add multi-tenant identifier. cert-20.7
  cel/cel_manager.c
  channels/chan_pjsip.c
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
  funcs/func_channel.c
  include/asterisk/cdr.h
  include/asterisk/cel.h
  include/asterisk/channel.h
  include/asterisk/channel_internal.h
  include/asterisk/event_defs.h
  include/asterisk/res_pjsip.h
  include/asterisk/stasis_channels.h
  main/cdr.c
  main/cel.c
  main/channel.c
  main/channel_internal_api.c
  main/cli.c
  main/event.c
  main/manager_channels.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  rest-api/api-docs/channels.json
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#741 channel: Add multi-tenant identifier.
  cel/cel_manager.c
  channels/chan_pjsip.c
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
  funcs/func_channel.c
  include/asterisk/cdr.h
  include/asterisk/cel.h
  include/asterisk/channel.h
  include/asterisk/channel_internal.h
  include/asterisk/event_defs.h
  include/asterisk/res_pjsip.h
  include/asterisk/stasis_channels.h
  main/cdr.c
  main/cel.c
  main/channel.c
  main/channel_internal_api.c
  main/cli.c
  main/event.c
  main/manager_channels.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  rest-api/api-docs/channels.json
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#836 manager.c: Fix FRACK when doing CoreShowChannelMap in DEVMODE
  main/manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#800 res_pjsip_notify: add dialplan application
  channels/pjsip/dialplan_functions_doc.xml
  configs/samples/extensions.conf.sample
  configs/samples/pjsip.conf.sample
  configs/samples/pjsip_notify.conf.sample
  res/res_pjsip_notify.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#833 chan_mobile: decrease CHANNEL_FRAME_SIZE to prevent delay
  addons/chan_mobile.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress

#838 Update version for Asterisk 22
  configure
  configure.ac
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#839 Prepare for Asterisk 23
  include/asterisk/manager.h
  rest-api/resources.json
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#842 alembic: Make 'revises' header comment match reality. (cert-18.9)
  contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#840 alembic: Make 'revises' header comment match reality.
  contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#844 res_pjsip_logger.c: Fix 'OPTIONS' tab completion.
  res/res_pjsip_logger.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#855 stir_shaken.conf.sample: Fix bad references to private_key_path
  configs/samples/stir_shaken.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
