Repository asterisk/asterisk, pull requests merged in 2024-02, with the labels that each got.

#570 app_chanspy: Add 'D' option for dual-channel audio
  apps/app_chanspy.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#568 utils: Make behavior of ast_strsep* match strsep.
  include/asterisk/strings.h
  main/utils.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#490 res_pjsip_outbound_registration.c: Add User-Agent-Header override
  contrib/ast-db-manage/config/versions/24c12d8e9014_add_user_agent_header_to_ps_.py
  res/res_pjsip_outbound_registration.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#576 app_speech_utils.c: Allow partial speech results.
  apps/app_speech_utils.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#577 Upgrade bundled pjproject to 2.14.
  third-party/pjproject/patches/0010-Make-sure-that-NOTIFY-tdata-is-set-before-sending-it_new-129fb323a66dd1fd16880fe5ba5e6a57.patch
  third-party/pjproject/patches/0020-log-dropped-packet-in-debug.patch
  third-party/pjproject/pjproject-2.13.1.tar.bz2.md5
  third-party/pjproject/pjproject-2.14.tar.bz2.md5
  third-party/versions.mak
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#587 configure: Rerun bootstrap on modern platform.
  configure
  include/asterisk/autoconfig.h.in
  menuselect/autoconfig.h.in
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#603 configure: Rerun bootstrap on modern platform.
  configure
  include/asterisk/autoconfig.h.in
  menuselect/autoconfig.h.in
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#604 configure: Rerun bootstrap on modern platform.
  configure
  include/asterisk/autoconfig.h.in
  menuselect/autoconfig.h.in
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#605 configure: Rerun bootstrap on modern platform.
  configure
  include/asterisk/autoconfig.h.in
  menuselect/autoconfig.h.in
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#583 Reduce startup/shutdown verbose logging
  apps/app_amd.c
  codecs/codec_speex.c
  main/bridge.c
  main/bucket.c
  main/cdr.c
  main/channel.c
  main/codec.c
  main/config.c
  main/dns_core.c
  main/file.c
  main/format.c
  main/format_cache.c
  main/image.c
  main/indications.c
  main/loader.c
  main/manager.c
  main/message.c
  main/pbx.c
  main/pbx_app.c
  main/pbx_functions.c
  main/refer.c
  main/rtp_engine.c
  main/sorcery.c
  main/translate.c
  res/res_agi.c
  res/res_audiosocket.c
  res/res_clialiases.c
  res/res_http_websocket.c
  res/res_speech.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#606 pjsip show channelstats: Prevent possible segfault when faxing
  channels/pjsip/cli_commands.c
  main/rtp_engine.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#596 dsp.c: Fix and improve potentially inaccurate log message.
  main/dsp.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#578 pseudo-MOS calculation formula change
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#615 strings.h: Ensure ast_str_buffer(…) returns a 0 terminated string.
  include/asterisk/strings.h
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#618 README.md: Removed outdated link
  README.md
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#585 translate.c: implement new direct comp table mode
  main/translate.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#628 alembic: Synchronize alembic heads between supported branches.
  contrib/ast-db-manage/config/versions/24c12d8e9014_dummy_migration.py
Labels: cherry-pick-testing-in-progress, cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#524 Stir/Shaken Refactor
  configs/samples/extconfig.conf.sample
  configs/samples/sorcery.conf.sample
  configs/samples/stir_shaken.conf.sample
  contrib/ast-db-manage/config/versions/bd335bae5d33_create_stir_shaken_tn_table.py
  include/asterisk/astdb.h
  include/asterisk/res_pjsip.h
  include/asterisk/res_pjsip_session.h
  include/asterisk/res_stir_shaken.h
  main/db.c
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_caller_id.c
  res/res_pjsip_session.c
  res/res_pjsip_session.exports.in
  res/res_pjsip_session/pjsip_session.h
  res/res_pjsip_session/pjsip_session_reason_header.c
  res/res_pjsip_stir_shaken.c
  res/res_stir_shaken.c
  res/res_stir_shaken/attestation.c
  res/res_stir_shaken/attestation.h
  res/res_stir_shaken/attestation_config.c
  res/res_stir_shaken/certificate.c
  res/res_stir_shaken/certificate.h
  res/res_stir_shaken/common_config.c
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/crypto_utils.c
  res/res_stir_shaken/crypto_utils.h
  res/res_stir_shaken/curl.c
  res/res_stir_shaken/curl.h
  res/res_stir_shaken/curl_utils.c
  res/res_stir_shaken/curl_utils.h
  res/res_stir_shaken/general.c
  res/res_stir_shaken/general.h
  res/res_stir_shaken/profile.c
  res/res_stir_shaken/profile.h
  res/res_stir_shaken/profile_config.c
  res/res_stir_shaken/profile_private.h
  res/res_stir_shaken/stir_shaken.c
  res/res_stir_shaken/stir_shaken.h
  res/res_stir_shaken/stir_shaken_doc.xml
  res/res_stir_shaken/store.c
  res/res_stir_shaken/tn_config.c
  res/res_stir_shaken/verification.c
  res/res_stir_shaken/verification.h
  res/res_stir_shaken/verification_config.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
