Repository asterisk/asterisk, pull requests merged in 2024-12, with the labels that each got.

#1002 manager.c: Add Processed Call Count to CoreStatus output
  main/manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1005 Fix bridged_payload matching with sample rate for DTMF
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#912 res_rtp_asterisk.c: Set mark on rtp when timestamp skew is too big
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1001 res_curl.conf.sample: clean up sample configuration and add new SSL options.
  configs/samples/res_curl.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#852 audiohook.c: resolving the issue with audiohook both reading when packet loss on one side of the call
  main/audiohook.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1014 chan_pjsip: Send VIDUPDATE RTP frame for all H.264 streams
  channels/chan_pjsip.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#414 chan_iax2: Add log message for rejected calls.
  channels/chan_iax2.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1011 func_uuid: Add a new dialplan function to generate UUIDs
  funcs/func_uuid.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1017 format_gsm.c: Added mime type
  formats/format_gsm.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#245 config.c: Make ast_variable_retrieve return last match.
  main/config.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1024 Allow C++ source files (as extension .cc) in the main directory
  main/Makefile
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1022 app_queue: indicate the paused state in queue_log (ADDMEMBER event)
  apps/app_queue.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1025 res_odbc: release threads from potential starvation.
  res/res_odbc.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1019 res_pjsip: Add new AOR option "qualify_2xx_only"
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/44bd6dd914fa_add_qualify_2xx_only_option.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/location.c
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_options.c
  res/res_pjsip_registrar.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
