Repository asterisk/asterisk, pull requests merged in 2024-05, with the labels that each got.

#247 res_pjsip_logger: Preserve logging state on reloads.
  res/res_pjsip_logger.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#728 res/stasis/control.c: include signal.h
  res/stasis/control.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#700 rtp_engine: add support for multirate RFC2833 digits
  include/asterisk/rtp_engine.h
  main/rtp_engine.c
  res/res_pjsip_sdp_rtp.c
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#739 Revert "res_pjsip_endpoint_identifier_ip: Add endpoint identifier transport address."
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/bd9c5159c7ea_revert_d5122576cca8_add_transport_.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_endpoint_identifier_ip.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
