Repository asterisk/asterisk, pull requests merged in 2024-11, with the labels that each got.

#965 app_mixmonitor: Add 'D' option for dual-channel audio.
  apps/app_mixmonitor.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#973 res_srtp: Change Unsupported crypto suite msg from verbose to debug
  res/res_srtp.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#966 app_mixmonitor: Add 'D' option for dual-channel audio. (certified/18.9)
  apps/app_mixmonitor.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#952 func_evalexten: Add EVAL_SUB function.
  funcs/func_evalexten.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#961 config.c Make ast_variable_update update last match.
  main/config.c
Labels: pre-merge-checks-passed, merge-failed, merge-in-progress, pr-submit-tests-passed

#969 pjsip_transport_events: handle multiple addresses for a domain
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_transport_events.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#983 res_pjsip: Move tenantid to end of ast_sip_endpoint
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_configuration.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#984 res_pjsip: Move tenantid to end of ast_sip_endpoint (cert-18.9 only)
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_configuration.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#991 func_pjsip_aor/contact: Fix documentation for contact ID
  funcs/func_pjsip_aor.c
  funcs/func_pjsip_contact.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#975 samples: remove and/or change some wiki mentions
  configs/samples/chan_dahdi.conf.sample
  configs/samples/extensions.conf.sample
  configs/samples/pjsip.conf.sample
  configs/samples/res_snmp.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#986 res_pjsip.c: Fix Contact header rendering for IPv6 addresses.
  res/res_pjsip.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#981 res_pjsip: Add new endpoint option "suppress_moh_on_sendonly" (cert-18.9 only)
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_sdp_rtp.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#980 res_pjsip: Add new endpoint option "suppress_moh_on_sendonly"
  configs/samples/pjsip.conf.sample
  contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
  include/asterisk/res_pjsip.h
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip_sdp_rtp.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#996 res_pjsip: Change suppress_moh_on_sendonly to OPT_BOOL_T
  contrib/ast-db-manage/README.md
  contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
  res/res_pjsip/pjsip_configuration.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#987 res_stir_shaken: Allow sending Identity headers for unknown TNs
  configs/samples/stir_shaken.conf.sample
  res/res_stir_shaken/attestation_config.c
  res/res_stir_shaken/common_config.h
  res/res_stir_shaken/crypto_utils.c
  res/res_stir_shaken/profile_config.c
  res/res_stir_shaken/stir_shaken_doc.xml
  res/res_stir_shaken/tn_config.c
  res/res_stir_shaken/verification_config.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#989 func_curl.c: Add additional CURL options for SSL requests
  funcs/func_curl.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress
