Repository asterisk/asterisk, pull requests merged in 2024-06, with the labels that each got.

#749 file.h: Rename function argument to avoid C++ keyword clash.
  include/asterisk/file.h
  main/file.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#753 chan_ooh323: Fix R/0 typo in docs
  addons/chan_ooh323.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#752 asterisk.c: Don't log an error if .asterisk_history does not exist.
  main/asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-failed, merge-in-progress, pr-submit-tests-failed

#737 Permit multiple attempts to load PostgreSQL CDR module.
  cdr/cdr_pgsql.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-failed, pr-submit-tests-passed

#746 xml.c: Update deprecated libxml2 API usage.
  main/xml.c
  res/res_calendar_caldav.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#762 Show configured cache dir
  main/asterisk.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#764 manager.c: Properly terminate `CoreShowChannelMap` event.
  main/manager.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#758 pjsip: Add PJSIP_PARSE_URI_FROM dialplan function.
  channels/chan_pjsip.c
  channels/pjsip/dialplan_functions.c
  channels/pjsip/dialplan_functions_doc.xml
Labels: cherry-pick-checks-passed, cherry-pick-gates-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#771 pbx.c: expand fields width of "core show hints"
  main/pbx.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#766 app_queue: Add option to not log Restricted Caller ID to queue_log
  apps/app_queue.c
  configs/samples/queues.conf.sample
  contrib/ast-db-manage/config/versions/2b7c507d7d12_add_queue_log_option_log_restricted_.py
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#712 app_voicemail_odbc: Allow audio to be kept on disk
  apps/app_voicemail.c
  configs/samples/voicemail.conf.sample
  main/app.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#724 app_voicemail_odbc: Allow audio to be kept on disk - 18,20
  apps/app_voicemail.c
  configs/samples/voicemail.conf.sample
  main/app.c
Labels: cherry-pick-checks-passed, cherry-pick-gates-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#784 stasis_channels: Use uniqueid and name to delete old snapshots
  main/stasis_channels.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-failed, merge-in-progress, pr-submit-tests-passed
