Repository asterisk/asterisk, pull requests merged in 2025-09, with the labels that each got.

#1411 app_waitforsilence.c: Use milliseconds to calculate timeout time
  apps/app_waitforsilence.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1410 app_queue.c: Add new global 'log_unpause_on_reason_change'
  apps/app_queue.c
  configs/samples/queues.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1415 chan_websocket.c: Add DTMF messages
  channels/chan_websocket.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1463 app_externalivr: Prevent out-of-bounds read during argument processing.
  apps/app_externalivr.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1473 Fix some doxygen, typos and whitespace
  agi/eagi-sphinx-test.c
  apps/app_dial.c
  apps/app_queue.c
  channels/chan_pjsip.c
  configs/samples/manager.conf.sample
  include/asterisk/config_options.h
  include/asterisk/logger.h
  include/asterisk/refer.h
  main/config_options.c
  main/features.c
  res/res_fax.c
  res/res_pjsip_session.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1471 Fix some doxygen, typos and whitespace
  agi/eagi-sphinx-test.c
  apps/app_dial.c
  apps/app_queue.c
  channels/chan_pjsip.c
  configs/samples/manager.conf.sample
  include/asterisk/config_options.h
  include/asterisk/logger.h
  include/asterisk/refer.h
  main/config_options.c
  main/features.c
  res/res_fax.c
  res/res_pjsip_session.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1476 sorcery: Move from threadpool to taskpool.
  main/sorcery.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1480 ARI: The bridges play and record APIs now handle sample rates > 8K correctly.
  res/ari/resource_bridges.c
  res/ari/resource_bridges.h
  res/res_ari_bridges.c
  rest-api/api-docs/bridges.json
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1484 sig_analog: Eliminate potential timeout with Last Number Redial.
  channels/sig_analog.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1486 func_scramble: Add example to XML documentation.
  funcs/func_scramble.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
