Repository asterisk/asterisk, pull requests merged in 2025-02, with the labels that each got.

#1100 utils: Remove libdb and astdb conversion scripts.
  Makefile
  doc/astdb2bdb.8
  doc/astdb2sqlite3.8
  main/db.c
  utils/Makefile
  utils/astdb2bdb.c
  utils/astdb2sqlite3.c
  utils/db1-ast/Makefile
  utils/db1-ast/btree/bt_close.c
  utils/db1-ast/btree/bt_conv.c
  utils/db1-ast/btree/bt_debug.c
  utils/db1-ast/btree/bt_delete.c
  utils/db1-ast/btree/bt_get.c
  utils/db1-ast/btree/bt_open.c
  utils/db1-ast/btree/bt_overflow.c
  utils/db1-ast/btree/bt_page.c
  utils/db1-ast/btree/bt_put.c
  utils/db1-ast/btree/bt_search.c
  utils/db1-ast/btree/bt_seq.c
  utils/db1-ast/btree/bt_split.c
  utils/db1-ast/btree/bt_utils.c
  utils/db1-ast/btree/btree.h
  utils/db1-ast/btree/extern.h
  utils/db1-ast/db/db.c
  utils/db1-ast/hash/README
  utils/db1-ast/hash/extern.h
  utils/db1-ast/hash/hash.c
  utils/db1-ast/hash/hash.h
  utils/db1-ast/hash/hash_bigkey.c
  utils/db1-ast/hash/hash_buf.c
  utils/db1-ast/hash/hash_func.c
  utils/db1-ast/hash/hash_log2.c
  utils/db1-ast/hash/hash_page.c
  utils/db1-ast/hash/hsearch.c
  utils/db1-ast/hash/ndbm.c
  utils/db1-ast/hash/page.h
  utils/db1-ast/hash/search.h
  utils/db1-ast/include/circ-queue.h
  utils/db1-ast/include/compat.h
  utils/db1-ast/include/db.h
  utils/db1-ast/include/mpool.h
  utils/db1-ast/include/ndbm.h
  utils/db1-ast/libdb.map
  utils/db1-ast/mpool/README
  utils/db1-ast/mpool/mpool.c
  utils/db1-ast/recno/extern.h
  utils/db1-ast/recno/rec_close.c
  utils/db1-ast/recno/rec_delete.c
  utils/db1-ast/recno/rec_get.c
  utils/db1-ast/recno/rec_open.c
  utils/db1-ast/recno/rec_put.c
  utils/db1-ast/recno/rec_search.c
  utils/db1-ast/recno/rec_seq.c
  utils/db1-ast/recno/rec_utils.c
  utils/db1-ast/recno/recno.h
  utils/utils.xml
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1103 func_strings.c: Prevent SEGV in HASH single-argument mode.
  funcs/func_strings.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1115 channel.c: Remove dead AST_GENERATOR_FD code.
  include/asterisk/channel.h
  main/channel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#962 ARI/pjsip: Make it possible to control transfers through ARI (master,22 only)
  channels/chan_pjsip.c
  channels/pjsip/dialplan_functions.c
  channels/pjsip/dialplan_functions_doc.xml
  channels/pjsip/include/dialplan_functions.h
  include/asterisk/frame.h
  include/asterisk/refer.h
  include/asterisk/res_pjsip_session.h
  include/asterisk/stasis_channels.h
  main/refer.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/ari/resource_channels.c
  res/ari/resource_channels.h
  res/res_ari_channels.c
  res/res_pjsip_refer.c
  rest-api/api-docs/channels.json
  rest-api/api-docs/events.json
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1102 ARI/pjsip: Make it possible to control transfers through ARI (21,20 only)
  channels/chan_pjsip.c
  channels/pjsip/dialplan_functions.c
  channels/pjsip/dialplan_functions_doc.xml
  channels/pjsip/include/dialplan_functions.h
  include/asterisk/frame.h
  include/asterisk/refer.h
  include/asterisk/res_pjsip_session.h
  include/asterisk/stasis_channels.h
  main/refer.c
  main/stasis_channels.c
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/ari/resource_channels.c
  res/ari/resource_channels.h
  res/res_ari_channels.c
  res/res_pjsip_refer.c
  rest-api/api-docs/channels.json
  rest-api/api-docs/events.json
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1110 resource_channels.c: Fix memory leak in ast_ari_channels_external_media.
  res/ari/resource_channels.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1113 res_stir_shaken: Allow missing or anonymous CID to continue to the dialplan.
  include/asterisk/res_stir_shaken.h
  res/res_pjsip_stir_shaken.c
  res/res_stir_shaken/verification.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1120 res_config_pgsql: Fix regression that removed dbname config.
  res/res_config_pgsql.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1125 bridge_channel: don't set cause code on channel during bridge delete if already set
  main/bridge_channel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-failed, merge-in-progress, pr-submit-tests-failed

#1094 bridging: Fix multiple bridging issues causing SEGVs and FRACKs.
  include/asterisk/bridge.h
  include/asterisk/stasis_bridges.h
  main/bridge.c
  main/stasis_bridges.c
  res/ari/resource_bridges.c
  res/ari/resource_bridges.h
  res/res_ari_bridges.c
  res/res_stasis.c
  res/stasis/stasis_bridge.c
  rest-api/api-docs/bridges.json
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1107 docs: Fix various typos in main/
  main/acl.c
  main/aoc.c
  main/ast_expr2.c
  main/ast_expr2.y
  main/astmm.c
  main/astobj2_container.c
  main/audiohook.c
  main/bridge.c
  main/bridge_basic.c
  main/bridge_channel.c
  main/callerid.c
  main/ccss.c
  main/cdr.c
  main/channel.c
  main/cli.c
  main/config_options.c
  main/core_local.c
  main/db.c
  main/devicestate.c
  main/dns.c
  main/enum.c
  main/features_config.c
  main/file.c
  main/fixedjitterbuf.c
  main/json.c
  main/loader.c
  main/manager.c
  main/manager_channels.c
  main/manager_doc.xml
  main/message.c
  main/pbx.c
  main/pbx_app.c
  main/pbx_functions.c
  main/pickup.c
  main/rtp_engine.c
  main/say.c
  main/stasis.c
  main/stasis_bridges.c
  main/stdtime/localtime.c
  main/stun.c
  main/taskprocessor.c
  main/udptl.c
  main/utils.c
  main/xml.c
  main/xmldoc.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1111 docs: Fix various typos in channels/
  channels/chan_dahdi.c
  channels/chan_iax2.c
  channels/chan_motif.c
  channels/chan_unistim.c
  channels/console_gui.c
  channels/console_video.c
  channels/iax2/include/astobj.h
  channels/iax2/include/firmware.h
  channels/iax2/include/parser.h
  channels/iax2/include/provision.h
  channels/pjsip/dialplan_functions_doc.xml
  channels/sig_analog.c
  channels/sig_pri.c
  channels/sig_pri.h
  channels/sig_ss7.h
  channels/vcodecs.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1121 docs: Fix typos in cdr/
  cdr/cdr_beanstalkd.c
  cdr/cdr_custom.c
  cdr/cdr_pgsql.c
  cdr/cdr_sqlite3_custom.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
