Repository asterisk/asterisk, pull requests merged in 2025-08, with the labels that each got.

#1342 app_queue: Remove redundant/deprecated function.
  apps/app_queue.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1348 func_dialplan: Remove deprecated/redundant function.
  funcs/func_dialplan.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1354 file.c: with "sounds_search_custom_dir = yes", search "custom" directory
  main/file.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed, has-pr-checklist

#1350 res_pjsip_diversion: resolve race condition between Diversion header processing and redirect
  res/res_pjsip_diversion.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1360 Update version for Asterisk 23
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  menuselect/autoconfig.h.in
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1362 Prepare master for Asterisk 24
  include/asterisk/manager.h
  rest-api/resources.json
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1355 pbx_lua.c: segfault when pass null data to term_color function
  pbx/pbx_lua.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1367 func_frame_drop: Handle allocation failure properly.
  funcs/func_frame_drop.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1370 test_res_prometheus: Fix compilation failure on Debian 13.
  tests/test_res_prometheus.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1372 func_frame_drop: Add debug messages for dropped frames.
  funcs/func_frame_drop.c
  main/channel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1368 xmldoc.c: Fix rendering of CLI output.
  main/xmldoc.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1407 res_pjsip_authenticator_digest: Fix SEGV if get_authorization_hdr returns NULL.
  res/res_pjsip_authenticator_digest.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
