Repository asterisk/asterisk, pull requests merged in 2025-06, with the labels that each got.

#1188 app_sms.c: Fix sending and receiving SMS messages in protocol 2
  apps/app_sms.c
Labels: cherry-pick-checks-failed, pre-merge-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1104 res_musiconhold: Appropriately lock channel during start.
  res/res_musiconhold.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed, has-pr-checklist

#1275 pbx.c: when set flag AST_SOFTHANGUP_ASYNCGOTO, ast_explicit_goto should return -1.
  include/asterisk/pbx.h
  main/pbx.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
