Repository asterisk/asterisk, pull requests merged in 2025-05, with the labels that each got.

#1231 lock.h: Add include for string.h when DEBUG_THREADS is defined.
  include/asterisk/lock.h
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1089 app_sms: Ignore false positive stringop-overflow warning.
  apps/Makefile
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1227 Alternate Channel Storage Backends
  Makefile
  configs/samples/asterisk.conf.sample
  include/asterisk/channel.h
  include/asterisk/channel_internal.h
  include/asterisk/options.h
  main/Makefile
  main/asterisk.c
  main/channel.c
  main/channel_internal_api.c
  main/channel_private.h
  main/channelstorage.c
  main/channelstorage.h
  main/channelstorage_ao2_legacy.c
  main/channelstorage_cpp_map_name_id.cc
  main/channelstorage_makeopts.xml
  main/options.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1235 chan_pjsip: Serialize INVITE creation on DTMF attended transfer
  channels/chan_pjsip.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1237 res_pjsip_nat.c: Do not overwrite transfer host
  res/res_pjsip_nat.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1232 manager.c: Invalid ref-counting when purging events
  main/manager.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1244 menuselect: Fix GTK menu callbacks for Fedora 42 compatibility
  menuselect/menuselect_gtk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1247 res_audiosocket.c: Add retry mechanism for reading data from AudioSocket
  res/res_audiosocket.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1256 res_pjsip_messaging.c: Mask control characters in received From display name
  res/res_pjsip_messaging.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed, has-pr-checklist

#1257 asterisk.c: Add option to restrict shell access from remote consoles.
  configs/samples/asterisk.conf.sample
  configs/samples/cli_permissions.conf.sample
  include/asterisk/options.h
  main/asterisk.c
  main/options.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, pr-submit-tests-passed
