Repository asterisk/asterisk, pull requests merged in 2025-04, with the labels that each got.

#1174 ARI: REST over Websocket
  include/asterisk/ari.h
  include/asterisk/http.h
  include/asterisk/json.h
  main/http.c
  main/json.c
  res/Makefile
  res/ari/ari_model_validators.c
  res/ari/ari_model_validators.h
  res/ari/ari_websocket_requests.c
  res/ari/ari_websockets.c
  res/ari/ari_websockets.h
  res/ari/internal.h
  res/ari/resource_events.c
  res/ari/resource_events.h
  res/res_ari.c
  res/res_ari_events.c
  rest-api-templates/ari_resource.h.mustache
  rest-api-templates/res_ari_resource.c.mustache
  rest-api/api-docs/events.json
  tests/test_ari.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1187 ari_websockets: Fix frack if ARI config fails to load.
  res/ari/ari_websockets.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1191 app_confbridge: Prevent crash when publishing channel-less event.
  apps/confbridge/confbridge_manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1196 asterisk.c: Add "pre-init" and "pre-module" capability to cli.conf. (20 only)
  configs/samples/cli.conf.sample
  main/asterisk.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed, has-pr-checklist

#1194 asterisk.c: Add "pre-init" and "pre-module" capability to cli.conf.
  configs/samples/cli.conf.sample
  main/asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1133 Add log-caller-id-name option to log Caller ID Name in queue log
  apps/app_queue.c
  configs/samples/queues.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1198 channel: Always provide cause code in ChannelHangupRequest.
  main/channel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, pr-submit-tests-passed

#1160 action_redirect: remove after_bridge_goto_info
  main/manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1199 contrib: Add systemd service and timer files for malloc trim.
  contrib/systemd/asterisk-malloc-trim.service
  contrib/systemd/asterisk-malloc-trim.timer
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1200 Prequisites for ARI Outbound Websockets
  include/asterisk/http.h
  include/asterisk/http_websocket.h
  include/asterisk/md5.h
  include/asterisk/stasis_app.h
  include/asterisk/tcptls.h
  main/http.c
  main/md5.c
  main/tcptls.c
  res/res_http_websocket.c
  res/res_stasis.c
  res/res_stasis_device_state.c
  res/stasis/control.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1195 res_pjproject: Fix DTLS client check failing on some platforms
  configure
  configure.ac
  include/asterisk/autoconfig.h.in
  res/res_pjproject.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1205 pbx_ael: unregister AELSub application and CLI commands on module load failure
  pbx/pbx_ael.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1207 chan_iax2: Minor improvements to documentation and warning messages.
  channels/chan_iax2.c
  channels/iax2/parser.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1210 docs: Fix typos in apps/
  apps/app_audiosocket.c
  apps/app_cdr.c
  apps/app_confbridge.c
  apps/app_dial.c
  apps/app_echo.c
  apps/app_externalivr.c
  apps/app_jack.c
  apps/app_meetme.c
  apps/app_minivm.c
  apps/app_mixmonitor.c
  apps/app_morsecode.c
  apps/app_mp3.c
  apps/app_queue.c
  apps/app_saycounted.c
  apps/app_skel.c
  apps/app_sms.c
  apps/app_voicemail.c
  apps/app_waitforsilence.c
  apps/confbridge/conf_config_parser.c
  apps/confbridge/include/confbridge.h
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1193 docs: Fix typos in apps/
  apps/app_audiosocket.c
  apps/app_cdr.c
  apps/app_confbridge.c
  apps/app_dial.c
  apps/app_echo.c
  apps/app_externalivr.c
  apps/app_jack.c
  apps/app_meetme.c
  apps/app_minivm.c
  apps/app_mixmonitor.c
  apps/app_morsecode.c
  apps/app_mp3.c
  apps/app_queue.c
  apps/app_saycounted.c
  apps/app_skel.c
  apps/app_sla.c
  apps/app_sms.c
  apps/app_voicemail.c
  apps/app_waitforsilence.c
  apps/confbridge/conf_config_parser.c
  apps/confbridge/include/confbridge.h
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1225 app_meetme: Remove inaccurate removal version from xmldocs.
  apps/app_meetme.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1223 func_callerid: Always format ANI2 as two digits.
  funcs/func_callerid.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1221 res_pjsip_caller_id: Also parse URI parameters for ANI2.
  res/res_pjsip_caller_id.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
