Repository asterisk/asterisk, pull requests merged in 2025-07, with the labels that each got.

#1285 bundled_pjproject: Avoid deadlock between transport and transaction
  third-party/pjproject/patches/0010-Avoid_deadlock_between_transport_and_transaction.patch
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1267 Media over Websocket Channel Driver
  channels/chan_websocket.c
  include/asterisk/http_websocket.h
  main/channel.c
  res/ari/resource_channels.c
  res/ari/resource_channels.h
  res/res_ari_channels.c
  res/res_http_websocket.c
  rest-api/api-docs/channels.json
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1277 chan_pjsip.c: Change SSRC after media source change
  channels/chan_pjsip.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1294 res_agi: Remove deprecated DeadAGI application.
  res/res_agi.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1318 res_agi: Increase AGI command buffer size from 2K to 8K
  res/res_agi.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1314 options: Change ast_options from ast_flags to ast_flags64.
  include/asterisk/options.h
  include/asterisk/utils.h
  main/asterisk.c
  main/cli.c
  main/loader.c
  main/manager.c
  main/options.c
  main/pbx.c
  main/plc.c
  res/res_pjsip/pjsip_distributor.c
  res/res_pjsip_mwi.c
  res/res_pjsip_pubsub.c
  utils/extconf.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
