Repository asterisk/asterisk, pull requests merged in 2025-10, with the labels that each got.

#1490 config_options.c: Improve misleading warning.
  main/config_options.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1506 res_fax: Add XML documentation for channel variables.
  res/res_fax.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1494 app_sf: Add post-digit timer option to ReceiveSF.
  apps/app_sf.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1500 func_math: Add DIGIT_SUM function.
  funcs/func_math.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1511 sig_analog: Allow '#' to end the inter-digit timeout when dialing.
  channels/sig_analog.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1515 func_channel: Allow R/W of ADSI CPE capability setting.
  funcs/func_channel.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1520 func_callerid: Document limitation of DNID fields.
  funcs/func_callerid.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1526 chan_websocket.c: Change payload references to command instead.
  channels/chan_websocket.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed
