Repository asterisk/asterisk, pull requests merged in 2025-03, with the labels that each got.

#1129 res_rtp_asterisk.c: Use correct timeout value for T.140 RED timer.
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1136 Revert "res_rtp_asterisk.c: Set Mark on rtp when timestamp skew is too big"
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1146 swagger_model.py: Fix invalid escape sequence in get_list_parameter_type().
  rest-api-templates/swagger_model.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1123 docs: AMI documentation fixes.
  apps/app_agent_pool.c
  main/stasis_bridges.c
  main/stasis_channels.c
  res/res_pjsip/pjsip_configuration.c
  res/res_pjsip/pjsip_manager.xml
  res/res_pjsip_outbound_registration.c
  res/res_pjsip_pubsub.c
  res/res_pjsip_registrar.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1151 config.c: Fix inconsistent pointer logic in ast_variable_update.
  main/config.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1150 fix: Correct default flag for tcp_keepalive_enable option
  res/res_pjsip/config_transport.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1154 res_rtp_asterisk.c: Don't truncate spec-compliant `ice-ufrag` or `ice-pwd`.
  res/res_rtp_asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1159 README.md: Updates and Fixes
  README.md
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1162 res_pjsip_outbound_registration.c: Remove xpointer reference to user_agent.
  res/res_pjsip_outbound_registration.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1165 res_config_curl.c: Remove unnecessary warnings.
  res/res_config_curl.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1163 documentation: Update Gosub, Goto, and add new documentationtype.
  apps/app_stack.c
  doc/appdocsxml.dtd
  main/pbx_builtins.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1169 [certified] documentation: Update Gosub, Goto, and add new documentationtype.
  apps/app_stack.c
  doc/appdocsxml.dtd
  main/pbx_builtins.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1172 file.c: missing "custom" sound files should not generate warning logs
  main/file.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1182 chan_pjsip: set correct Endpoint Device State on multiple channels
  channels/chan_pjsip.c
  res/res_pjsip/pjsip_config.xml
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1015 chan_pjsip: Add the same details as PJSIPShowContacts to the CLI via 'pjsip show contact'
  res/res_pjsip/location.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
