Repository asterisk/asterisk, pull requests merged in 2025-01, with the labels that each got.

#1034 Add ability to pass arguments to unit tests from the CLI
  include/asterisk/test.h
  main/test.c
  tests/test_skel.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1035 Header fixes for compiling C++ source files
  include/asterisk/astmm.h
  include/asterisk/lock.h
  include/asterisk/logger.h
  include/asterisk/strings.h
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1039 gcc14: Fix issues caught by gcc 14
  tests/test_message.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1040 gcc14: Fix issues caught by gcc 14 (branches <= 20)
  channels/sip/reqresp_parser.c
  tests/test_message.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1043 Upgrade bundled pjproject to 2.15.1
  third-party/pjproject/patches/0000-configure-ssl-library-path.patch
  third-party/pjproject/pjproject-2.14.1.tar.bz2.md5
  third-party/pjproject/pjproject-2.15.1.tar.bz2.md5
  third-party/versions.mak
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1030 chan_dahdi: Fix wrong channel state when RINGING recieved.
  channels/chan_dahdi.c
  include/asterisk/channelstate.h
  main/devicestate.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1041 Add C++ Standard detection to configure and fix a new C++20 compile issue
  autoconf/ast_cxx_check_std.m4
  autoconf/ax_cxx_compile_stdcxx.m4
  build_tools/menuselect-deps.in
  configure
  configure.ac
  contrib/scripts/install_prereq
  include/asterisk/autoconfig.h.in
  include/asterisk/strings.h
  menuselect/autoconfig.h.in
  menuselect/configure
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1042 normalize contrib/ast-db-manage/queue_log.ini.sample
  contrib/ast-db-manage/queue_log.ini.sample
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1047 config.c: Fix off-nominal reference leak.
  main/config.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#971 config.c: retain leading whitespace before comments
  main/config.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#972 Add SHA-256 and SHA-512-256 as authentication digest algorithms
  configs/samples/pjsip.conf.sample
  configure
  configure.ac
  contrib/ast-db-manage/config/versions/abdc9ede147d_add_fields_to_ps_auths_to_support_new_.py
  include/asterisk/autoconfig.h.in
  include/asterisk/res_pjsip.h
  res/res_pjproject.c
  res/res_pjsip/config_auth.c
  res/res_pjsip/config_global.c
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip/pjsip_distributor.c
  res/res_pjsip_authenticator_digest.c
  res/res_pjsip_outbound_authenticator_digest.c
  third-party/pjproject/configure.m4
  third-party/pjproject/patches/config_site.h
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1056 res_pjproject: Fix typo (OpenmSSL->OpenSSL)
  res/res_pjproject.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1051 res_config_pgsql: normalize database connection options
  configs/samples/res_pgsql.conf.sample
  res/res_config_pgsql.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1053 manager.c: Rename restrictedFile to is_restricted_file.
  main/manager.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1050 logger.c fix: malformed JSON template
  main/logger.c
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1048 samples: Use "asterisk" instead of "postgres" for username
  configs/samples/cdr_pgsql.conf.sample
  configs/samples/cel_pgsql.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1063 dialplan_functions_doc.xml: Document PJSIP_MEDIA_OFFER's `media` argument.
  channels/pjsip/dialplan_functions_doc.xml
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1057 docs: Enable since/version handling for XML, CLI and ARI documentation
  doc/appdocsxml.dtd
  include/asterisk/agi.h
  include/asterisk/manager.h
  include/asterisk/pbx.h
  include/asterisk/xmldoc.h
  main/config_options.c
  main/manager.c
  main/pbx_app.c
  main/pbx_functions.c
  main/xmldoc.c
  res/res_agi.c
  rest-api-templates/api.wiki.mustache
  rest-api-templates/swagger_model.py
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-failed, pr-submit-tests-passed

#1068 docs: Various XML fixes
  channels/pjsip/dialplan_functions_doc.xml
  main/bucket.c
  main/named_acl.c
  res/res_geolocation/geoloc_doc.xml
  res/res_http_media_cache.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#438 sig_analog: Add Last Number Redial feature.
  channels/chan_dahdi.c
  channels/chan_dahdi.h
  channels/sig_analog.c
  channels/sig_analog.h
  configs/samples/chan_dahdi.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1055 chan_iax2: Always set chosenformat upon call connection.
  channels/chan_iax2.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1065 ast_tls_cert: Add option to skip passphrase for CA private key.
  contrib/scripts/ast_tls_cert
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1071 res_pjsip_authenticator_digest: Fix issue with missing auth and DONT_OPTIMIZE
  res/res_pjsip_authenticator_digest.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1070 docs: Add version information to configObject and configOption XML elements (20 only)
  apps/app_agent_pool.c
  apps/app_skel.c
  apps/confbridge/conf_config_parser.c
  channels/chan_motif.c
  main/cdr.c
  main/cel.c
  main/features_config.c
  main/named_acl.c
  main/stasis.c
  main/udptl.c
  res/res_aeap.c
  res/res_ari.c
  res/res_geolocation/geoloc_doc.xml
  res/res_hep.c
  res/res_http_media_cache.c
  res/res_parking.c
  res/res_pjproject.c
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip_acl.c
  res/res_pjsip_endpoint_identifier_ip.c
  res/res_pjsip_notify.c
  res/res_pjsip_outbound_publish.c
  res/res_pjsip_outbound_registration.c
  res/res_pjsip_phoneprov_provider.c
  res/res_pjsip_publish_asterisk.c
  res/res_pjsip_pubsub.c
  res/res_prometheus.c
  res/res_resolver_unbound.c
  res/res_statsd.c
  res/res_stir_shaken/stir_shaken_doc.xml
  res/res_xmpp.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1069 docs: Add version information to configObject and configOption XML elements
  apps/app_agent_pool.c
  apps/app_skel.c
  apps/confbridge/conf_config_parser.c
  channels/chan_motif.c
  main/cdr.c
  main/cel.c
  main/features_config.c
  main/named_acl.c
  main/stasis.c
  main/udptl.c
  res/res_aeap.c
  res/res_ari.c
  res/res_geolocation/geoloc_doc.xml
  res/res_hep.c
  res/res_http_media_cache.c
  res/res_parking.c
  res/res_pjproject.c
  res/res_pjsip/pjsip_config.xml
  res/res_pjsip_acl.c
  res/res_pjsip_endpoint_identifier_ip.c
  res/res_pjsip_notify.c
  res/res_pjsip_outbound_publish.c
  res/res_pjsip_outbound_registration.c
  res/res_pjsip_phoneprov_provider.c
  res/res_pjsip_publish_asterisk.c
  res/res_pjsip_pubsub.c
  res/res_prometheus.c
  res/res_resolver_unbound.c
  res/res_statsd.c
  res/res_stir_shaken/stir_shaken_doc.xml
  res/res_xmpp.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1080 README.md, asterisk.c: Update Copyright Dates (cert-18.9 only)
  README.md
  main/asterisk.c
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1077 README.md, asterisk.c: Update Copyright Dates
  README.md
  main/asterisk.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1079 res_prometheus.c: Set Content-Type header on /metrics response.
  res/res_prometheus.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1082 LICENSE: Update company name, email, and address. (cert-18.9 only)
  LICENSE
Labels: pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1078 LICENSE: Update company name, email, and address.
  LICENSE
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1076 docs: Add version information to manager event instance XML elements
  apps/app_agent_pool.c
  apps/app_confbridge.c
  apps/app_meetme.c
  apps/app_minivm.c
  apps/app_mixmonitor.c
  apps/app_queue.c
  apps/app_stack.c
  apps/app_voicemail.c
  apps/confbridge/confbridge_manager.c
  build_tools/get_documentation
  cdr/cdr_manager.c
  cel/cel_manager.c
  channels/chan_dahdi.c
  channels/sig_pri.c
  funcs/func_global.c
  main/aoc.c
  main/asterisk.c
  main/channel.c
  main/core_local.c
  main/devicestate.c
  main/loader.c
  main/lock.c
  main/logger.c
  main/logger_doc.xml
  main/manager_bridges.c
  main/manager_channels.c
  main/manager_doc.xml
  main/manager_mwi.c
  main/pbx.c
  main/pickup.c
  main/presencestate.c
  main/rtp_engine.c
  main/security_events.c
  main/stasis.c
  main/stasis_bridges.c
  main/stasis_channels.c
  main/stasis_endpoints.c
  main/stasis_system.c
  res/parking/parking_manager.c
  res/res_agi.c
  res/res_fax.c
  res/res_manager_devicestate.c
  res/res_manager_presencestate.c
  res/res_mwi_external_ami.c
  res/res_pjsip/pjsip_manager.xml
Labels: cherry-pick-checks-passed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1087 res_pjsip: Fix startup/reload memory leak in config_auth.
  include/asterisk/res_pjsip.h
  res/res_pjsip/config_auth.c
  res/res_pjsip/config_global.c
  res/res_pjsip/pjsip_distributor.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1099 alembic: Database updates required.
  contrib/ast-db-manage/config/versions/44bd6dd914fa_add_qualify_2xx_only_option.py
  contrib/ast-db-manage/config/versions/abdc9ede147d_add_fields_to_ps_auths_to_support_new_.py
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed

#1098 res_pjsip_authenticator_digest: Make correct error messages appear again.
  res/res_pjsip_authenticator_digest.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#908 rtp.conf.sample: Correct stunaddr example.
  configs/samples/rtp.conf.sample
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1096 docs: Fix minor typo in MixMonitor AMI action
  apps/app_mixmonitor.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-failed

#1090 docs: Add version information to AGI command XML elements.
  res/res_agi.c
Labels: cherry-pick-checks-failed, pre-merge-checks-passed, merge-in-progress, pr-submit-tests-passed
